AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaAccountId:
    Description: Lambda Account ID
    MaxLength: '12'
    MinLength: '12'
    Type: String
    Default: "564707250760"
  ConformancePackName:
    Description: Conformance Pack Name
    Type: String
  TemplateS3Uri:
    Description: Conformance Pack S3 URI
    Type: String
Resources:
    CloudFormationOrgPack:
        Type: AWS::Config::OrganizationConformancePack
        Properties:
          ConformancePackInputParameters:
            - ParameterName: LambdaAccountId
              ParameterValue: !Ref LambdaAccountId
          OrganizationConformancePackName: !Ref ConformancePackName
          TemplateS3Uri: !Ref TemplateS3Uri
          ExcludedAccounts: 
            - 262534548841